Train Begin...
Episodes:   0%|                                                                   | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                         
경로 재계산 실패: AGV N, 현재 위치 (90, 12), 시작 위치 (90, 3), 목표 위치 (90, 3)
경로 재계산 실패: AGV C, 현재 위치 (23, 74), 시작 위치 (17, 77), 목표 위치 (17, 77)
경로 재계산 실패: AGV M, 현재 위치 (22, 74), 시작 위치 (26, 62), 목표 위치 (26, 62)
경로 재계산 실패: AGV C, 현재 위치 (23, 74), 시작 위치 (17, 77), 목표 위치 (17, 77)
경로 재계산 실패: AGV M, 현재 위치 (22, 74), 시작 위치 (26, 62), 목표 위치 (26, 62)
경로 재계산 실패: AGV C, 현재 위치 (23, 74), 시작 위치 (17, 77), 목표 위치 (17, 77)
경로 재계산 실패: AGV I, 현재 위치 (53, 80), 시작 위치 (53, 89), 목표 위치 (53, 89)
경로 재계산 실패: AGV M, 현재 위치 (22, 74), 시작 위치 (26, 62), 목표 위치 (26, 62)
경로 재계산 실패: AGV C, 현재 위치 (23, 74), 시작 위치 (17, 77), 목표 위치 (17, 77)
경로 재계산 실패: AGV M, 현재 위치 (22, 74), 시작 위치 (26, 62), 목표 위치 (26, 62)
  File "/home/js/DAA_CPS/train.py", line 109, in <module>
    train(config)
  File "/home/js/DAA_CPS/train.py", line 59, in train
    action = agent.act(state, env, agv_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/js/DAA_CPS/Agent.py", line 82, in act
    env.controller.perform_action(agv_id, action)
  File "/home/js/DAA_CPS/Controller.py", line 139, in perform_action
    self.replan_rout(agv_id)
  File "/home/js/DAA_CPS/Controller.py", line 147, in replan_rout
    current_goal = self.agv_rout[agv_id][-1]
                   ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
